### ISSUE TITLE
No templates found

### ISSUE THREAD

**Issue by talaikis** [matthisk/django-chart#1]
No templates found:
charting/async/html.html
charting/async/js.html
charting/chart.html

Probably something should go to documentation.

**Comment by matthisk** [comment]
Sorry for the delayed response. Could you elaborate a bit on the issue, when are you encountering it, which version of Django are you using? The templates are distributed with the libraries .whl package.

**Comment by talaikis** [comment]
OK, if I remember right, Templates weren't found, I was suing Django 1.10 with Python 3.6, fix was to copy templates to project folder.

**Comment by matthisk** [comment]
This probably has to do with 'APP_DIRS' not being enabled in your configuration:

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        ...
```

If you enable that it should pick up the templates. I am not sure if this is mentioned in the docs but will add that if it is not there.
