### ISSUE TITLE
Creating Custom Tick Formats

### ISSUE THREAD

**Issue by steadydoer** [matthisk/django-chart#10]
Hi, thank you for making this project. Please understand it even in my poor English. I would like to put a comma in the y axis value. So I make callback function. However, the ticks.callback method override does not work.

Is there a way to override the ticks.callback method?

Here is chart.js documentation about 'Creating Custom Tick Formats'
http://www.chartjs.org/docs/latest/axes/labelling.html#creating-custom-tick-formats

Thx

**Comment by matthisk** [comment]
Unfortunately it is not possible to do this at this time. There is already an issue open discussing the way we could enable callback methods with the library #7
