### ISSUE TITLE
Custom asynchronous filtering

### ISSUE THREAD

**Issue by MiltonLn** [matthisk/django-chart#11]
Hello,

Firstly, thanks for this awesome tool to generate charts in Django.

Secondly, is there a way to add custom asynchronous filters to the charts? suppose i have a bar chart with the amount of items sold on a year by item and i wish to add a selector to filter the chart dataset by month and it must load in an asynchronous way.

Is there possible with django-jchart at this moment? i have read the Asynchronous Chart section of the documentation but i think this is not what i'm looking for.

**Comment by slammer23** [comment]
Hi you can easily reach this with your data selection in django view.py. Just build a dropdown or a selection box, by changing that dropdown or selection box you can fire a HTML POST or GET. Catch that event in your views.py, filter the data you need to filter and re-create your chart with jchart.

BR

**Comment by matthisk** [comment]
@Slammer23 Thank you for answering this question. You are correct that it is not possible to filter values on the frontend so your approach would be the only solution. This library is meant to be used to render simple charts quickly from your Django codebase (without thinking about the JavaScript required to render these charts), that is why we do not support this type of additional filtering on the frontend.
