### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by PedroRamosRguez** [matthisk/django-chart#2]
Hi, i think that u have an error in the documentation. I mean, i followed step by step the configuration to render a plot and u have in the docs the url pattern like this 
```from jchart.views import ChartView

# LineChart is a class inheriting from jchart.Chart
line_chart = LineChart()

urlpatterns = [
    url(r'^charts/line_chart/$', ChartView.from_chart(line_chart), name='line_chart'),
]
```

When i try to render a template i got a json object not the plot . The issue is here **` ChartView.from_chart(line_chart)`** if I change that for this **`views.some_view`** i got the plot without problem.

In this stackoverflow thread, i got the answer for this issue [Link to resolve the issue](http://stackoverflow.com/questions/42270552/django-linechart-object-has-no-attribute-get).

I'm using Django 1.8 by the way. I hope this can help.

**Comment by matthisk** [comment]
Sorry for the delayed response. With asynchronous chart rendering you should use the `render_chart` template tag in your templates:

    {% render_chart 'line_chart' %}

Were you doing that? It should mention that in [docs](https://github.com/matthisk/django-jchart#------------asynchronous-charts----)

**Comment by PedroRamosRguez** [comment]
Hi, i didnt try that. I resolved my issue only putting my view  in url pattern. I mean, i used my view class to return a chart and the next step was to configure my url patter like this:
```

urlpatterns = [
    url(r'^charts/line_chart/$',views.some_view, name='line_chart'),
]
```
But no problem you can close the issue if that method works.
