### ISSUE TITLE
Chart Parameterization

### ISSUE THREAD

**Issue by kvdogan** [matthisk/django-chart#4]
Hi, 

Documentation seems obsolete for Chart Parameterization, Could you please provide an example?

**Comment by matthisk** [comment]
Sorry about that I updated the documentation but forgot to deploy to the docs website. The documentation is up to date now. Please let me know if you need any help with chart parameterization.

**Comment by vicvoncastle** [comment]
Edit to below: Clarifed now, in the tests section, you specify it as '1.0' but that was simply to test. It seems that the chart prefers milliseconds instead.
This may be a stupid question, but does the chart have to be async to support animation? Placing 'animation=Animation(duration=5.0)' and then passing that to options doesn't seem to do anything
